" Pathogen
execute pathogen#infect()

" General Settings
set nocompatible                        " Don't care vi
filetype on                             " Enable filetype detection
set hidden                              " Enable changed hidden buffers
set nobackup                            " Disable backup files
set nowritebackup                       " Don't create backup files
set noswapfile
set viminfo=""
 
" Gui Settings
colorscheme m2													" Use solarized colorscheme 
syntax on                               " Turn syntax higlighting on
 
" Status Line Settings
set laststatus=2
set statusline=%<\%n:%f\ %m%r%y%=%-35.(l:\ %l\ of\ %L,\ c:\ %c%V\ (%P)%)
 
" Window Settings
set number                              " Show line numbers
set splitright                          " Vertical split to right side
set scroll=5                            " Scroll 5 lines at a time

" Search Settings
set ignorecase                          " Disable search case sensitivity
set incsearch                           " Enable instant search 
set hlsearch                            " Highlight search term

" Indentation Settings
set tabstop=2                           " Tab lenght is 2 space
set softtabstop=2                       " Tab lenght is 2 space
set shiftwidth=2                        " Tab lenght is 2 space
" set expandtab                           " Use spaces instead of tabs
filetype plugin indent on               " Enable Automatic Indentation based on file type 

" Disable Arrow Keys
map <up> <nop>
map <down> <nop>
map <left> <nop>
map <right> <nop>
 
" " Experimental Settings
set smarttab
set nowrap
imap <tab> <c-x><c-o>
