"----------------------------------------------------------
" Plugins
"----------------------------------------------------------

" Auto install vim-plug if It's missing
if empty(glob('~/.vim/autoload/plug.vim'))
  silent !curl -fLo ~/.vim/autoload/plug.vim --create-dirs
    \ https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
  autocmd VimEnter * PlugInstall --sync | source $MYVIMRC
endif

" Start vim-plug
call plug#begin()

" Visual
" Plug 'bling/vim-airline'               " Improved status line
" Plug 'vim-airline/vim-airline-themes'
" Plug 'scrooloose/nerdtree'             " Adds file browser window
Plug 'junegunn/fzf'                    " Adds fuzzy finder
Plug 'junegunn/fzf.vim'
Plug 'w0rp/ale'                        " Shows inline lint errors
Plug 'liuchengxu/vim-which-key'        " Displays mappings for <leader> in window
Plug 'Kazark/vim-SimpleSmoothScroll'   " Slows down scroll speed
Plug 'Yggdroot/indentLine'             " Display indentation levels for spaces

" Text
Plug 'tpope/vim-commentary'            " Adds gc operator for toggling comments
Plug 'gokcehan/vim-opex'               " Adds gx operator to execute code
Plug 'tpope/vim-surround'              " Adds s text-object for surrounding ' } )
Plug 'michaeljsmith/vim-indent-object' " Adds i text-object for indentation
Plug 'bhurlow/vim-parinfer'            " Balances lisp parenthesis
Plug 'tpope/vim-endwise'               " Adds 'end' after def, if... in ruby/crystal
" Plug 'jiangmiao/auto-pairs'            " Adds closing ' ] } ) chars in insert mode

" Git
Plug 'airblade/vim-gitgutter'          " Shows unstaged lines on the file
Plug 'tpope/vim-fugitive'              " Adds :Gstatus, :Gcommit and more
Plug 'tpope/vim-rhubarb'               " Adds :Gbrowse for opening in Github
Plug 'junegunn/gv.vim'                 " Adds :GV command for viewing git logs
Plug 'oguzbilgic/vim-gdiff'            " Adds :Gdiff command 
Plug 'xuyuanp/nerdtree-git-plugin'     " Shows git status in the nerd tree
" Plug 'vim-scripts/gitignore'           " Makes vim use gitignore for 'wildignore'

" Compilers
Plug 'dgraham/vim-eslint'              " Adds eslint compiler. ':make .' populates quickfix
Plug 'tfnico/vim-gradle'

" Filetype
Plug 'rhysd/vim-crystal'               " Adds .cr file type support
Plug 'udalov/kotlin-vim'               " Adds .kt file type support
Plug 'pangloss/vim-javascript'         " Improves .js file type support
Plug 'kchmck/vim-coffee-script'        " Adds .coffee file type support
Plug 'leafgarland/typescript-vim'      " Adds .ts file type support
Plug 'dag/vim-fish'                    " Adds .fish file type support
Plug 'andreshazard/vim-freemarker'     " Adds .ftl file type support
Plug 'maxmellon/vim-jsx-pretty'        " Adds jsx support for .js and .jsx
Plug 'peitalin/vim-jsx-typescript'     " Adds .tsx file type support
" Plug 'vim-ruby/vim-ruby'

" Colorschemes
Plug 'morhetz/gruvbox'
Plug 'rakr/vim-one'
" Plug 'ajh17/Spacegray.vim'
" Plug 'felixhummel/setcolors.vim'       " :SetColors all then F8 to switch colorschemes
" Plug 'daviddavis/vim-colorpack'
" Plug 'noahfrederick/vim-hemisu'
" Plug 'junegunn/seoul256.vim'
" Plug 'vim-scripts/playroom'
" Plug 'lifepillar/vim-wwdc17-theme'
" Plug 'oguzbilgic/sexy-railscasts-theme'
" Plug 'cormacrelf/vim-colors-github'
" Plug 'cocopon/iceberg.vim'
" Plug 'tomasr/molokai'
" Plug 'nanotech/jellybeans.vim'

" End plugin list
call plug#end()

"----------------------------------------------------------
" Vim Settings
"----------------------------------------------------------

" General Settings
set hidden                             " Enable unsaved buffers to be hidden
" set clipboard=unnamed                  " Use system clipboard for copy/paste
set visualbell                         " Disable beeping by using visual bell
set history=500                        " Increase command history

" File type
filetype plugin indent on              " Enable filetype system

" Insert settings
set backspace=indent,eol,start         " Enable backspace for deleting after insert

" Backup settings
set nobackup                           " Disable backup files
set nowritebackup                      " No backup files
set noswapfile                         " No swap files

" Search Settings
set ignorecase                         " Disable search case sensitivity
set incsearch                          " Enable instant search
set hlsearch                           " Highlight search term

" Indentation Settings
set tabstop=2                          " Width of a tab character
set softtabstop=2                      " Tab length is 2 space
set shiftwidth=2                       " Tab length is 2 space
set smartindent                        " Add extra indent if new block started
set autoindent                         " Use current lines indent for new line
set expandtab                          " Insert <space> instead of tab
set smarttab

" Folding
" set foldmethod=indent                  " Fold based on indentation
set foldlevel=9                        " Fold all starting from the first
" set foldclose=all                      " Close folds if you leave them in any way
" set foldopen=all                       " Open folds if you touch them in any way
set foldnestmax=5                      " Fold only maximum of 5 levels of indentation
set fillchars+=fold:\                  " Don't use fold divider character

" Diff
set fillchars+=diff:\                  " Don't fill deleted diff lines
set diffopt+=vertical                  " Always show diffs in a vertical split

" Session
set sessionoptions-=options            " When saving session, don't store options

" Performance
set lazyredraw
set ttyfast

" Experimental: Enable project specific .vimrc
" Dangerous because untrust code can be executed
set exrc
set secure

" Completion
set completeopt-=preview

" Experimental: enable 'cursorline' only for the active window
augroup cursor_line_autocmds
  autocmd!
  autocmd VimEnter,WinEnter,BufWinEnter * setlocal cursorline
  autocmd WinLeave * setlocal nocursorline
augroup END

"----------------------------------------------------------
" UI Settings
"----------------------------------------------------------

" Colorscheme
if &background == 'dark'
  colorscheme gruvbox
else
  colorscheme one
endif

" Color Settings
syntax on
set t_Co=256                           " Enable 256 color

" UI Settings
" set mouse=a                            " Enable mouse
set showcmd                            " Show current command bottom right
set wildmenu                           " Show command line suggestions
set number                             " Show line numbers
set relativenumber                     " Show relative numbers
set nowrap                             " Disable  wrapping of long lines
set shortmess+=I                       " Hide Vim's welcome message

" Invisible Character
set list                               " Show invisible characters
set showbreak=↪\                       " Line breaks for wrap option
set listchars=tab:│\ ,nbsp:␣,trail:·,extends:⟩,precedes:⟨
" │ » → •

" Window Settings
" set laststatus=2                       " Always show window status line
set splitright                         " Vertical split to right side
set fillchars+=vert:\                  " Don't use window divider character

" Set truecolor for 16 million colors
" INFO: https://gist.github.com/XVilka/8346728
" BUG: This checks if vim is built with +termguicolors feature.
"      We need a way to check if the current terminal supports truecolor.
"      Hyper.js and Terminal.app don't support truecolor.
if has('termguicolors')
  set termguicolors
endif

if $TERM_PROGRAM == 'iTerm.app'
  " Undercurl escape characters
  " let &t_Cs = "\e[4:3m"
  " let &t_Ce = "\e[4:0m"

  " Change cursor in insert mode
  let &t_SI = "\<Esc>]50;CursorShape=1\x7"
  let &t_SR = "\<Esc>]50;CursorShape=2\x7"
  let &t_EI = "\<Esc>]50;CursorShape=0\x7"
endif

"----------------------------------------------------------
" Mappings
"----------------------------------------------------------

" Set <space> as the <leader> key
let g:mapleader = "\<space>"

" Disable Arrow Keys
map <up> <nop>
map <down> <nop>
map <left> <nop>
map <right> <nop>

" Experimental: Quickfix motions
nnoremap [q :cprevious<cr>
nnoremap ]q :cnext<cr>
nnoremap [Q :cfirst<cr>
nnoremap ]Q :clast<cr>

" Experimental: Location list motions
nnoremap [l :lprevious<cr>
nnoremap ]l :lnext<cr>
nnoremap [L :lfirst<cr>
nnoremap ]L :llast<cr>

" Experimental: Buffer motions
nnoremap [b :bprevious<cr>
nnoremap ]b :bnext<cr>
nnoremap [B :bfirst<cr>
nnoremap ]B :blast<cr>

" Open vimrc in a new tab
nnoremap <leader>ve :tabe $MYVIMRC<CR>
nnoremap <leader>vs :source $MYVIMRC<CR>

" Experimental: ZZ in insert mode
" inoremap ZZ <esc>ZZ

" Ipad Settings
" map! ` <ESC>
" vmap! ` <ESC>

" Exit visual mode immediately
" vmap <esc> <C-c>

"----------------------------------------------------------
" Vim Netrw Settings
"----------------------------------------------------------

" Hide info banner
let g:netrw_banner=0
let g:netrw_liststyle=3

"----------------------------------------------------------
" Colorscheme Settings & Overwrites
"----------------------------------------------------------

if g:colors_name == 'one' && &background == "light"
  let g:one_allow_italics = 1

  highlight clear Visual
  highlight clear Search
  highlight clear IncSearch
  highlight Visual guibg=#d7ffff
  highlight Search guibg=#fffc38 cterm=italic gui=italic

  highlight clear DiffAdd
  highlight clear DiffChange
  highlight clear DiffDelete
  highlight clear DiffText
  highlight DiffAdd    ctermbg=194 guibg=#e7feed
  highlight DiffChange ctermbg=230 guibg=#ffffd7
  highlight DiffDelete ctermbg=224 guibg=#feeef0
  highlight DiffText guibg=#ffe6bc

  " Fugitive objects use these groups
  highlight DiffFile guibg=NONE
  highlight DiffNewFile guibg=NONE
  highlight! link DiffAdded DiffAdd
  highlight! link DiffRemoved DiffDelete
  highlight! link DiffLine Folded

  highlight clear Folded
  highlight Folded guibg=#e8f1fb guifg=#868c90 cterm=italic

  " Remove underline
  highlight TabLine cterm=NONE gui=NONE
  highlight! link VertSplit StatusLine
end

if g:colors_name == 'spacegray'
  let g:spacegray_use_italics = 1

  highlight clear Todo

  highlight! link VertSplit StatusLineNC
  highlight! link TabLineFill StatusLineNC
  highlight! link TabLineSel StatusLine

  highlight DiffText guibg=#d88735 guifg=black cterm=italic,bold
  highlight DiffChange guibg=#815d3a guifg=black
  highlight Error cterm=NONE
  highlight SpellBad cterm=underline guibg=NONE

  " GitGutter
  highlight link GitGutterAdd String
  highlight link GitGutterChange Identifier
end

if g:colors_name == 'gruvbox'
  highlight! link Visual CursorLine
  highlight! link VertSplit StatusLineNC

  highlight! link StatusLineTerm StatusLine
  highlight! link StatusLineTermNC StatusLineNC

  highlight! link ALEError GruvboxRedBold
  highlight! link ALEErrorSign GruvboxRedBold

  highlight clear SignColumn
  highlight! link GitGutterAdd GruvboxGreen
  highlight! link GitGutterChange GruvboxYellow

  highlight! link gitcommitSummary GruvboxBlue

  highlight CursorLineNr guibg=NONE
end

"----------------------------------------------------------
" Experimental: Custom Commands
"----------------------------------------------------------

" Saves read only file with sudo
command Sudow w !sudo tee %

" Resizes current window to fit contents
command Fit execute('resize ' . line('$'))

" SynStack -----------------------------------------------

" Prints the highlight groups for the word under the cursor
function! SynStack()
  if !exists("*synstack")
    return
  endif
  echo map(synstack(line('.'), col('.')), 'synIDattr(v:val, "name")')
endfunc

command SynStack call SynStack()

" Note ---------------------------------------------------

" Experimental: Navigate to notes
function! Note(period)
  let day = strftime('%Y-%m-%d')
  let week = strftime('%Y-%W')
  let folder = '~/Code/oguzbilgic/self/'
  let daily_file = folder . day . '.md'
  let weekly_file = folder . 'week/' . week . '.md'

  if a:period == "week"
    execute "tabedit" . weekly_file
  else
    execute "tabedit" . daily_file
  endif
endfunc

nnoremap <leader>vd :call Note("day")<CR>
nnoremap <leader>vw :call Note("week")<CR>
